package view;

import javax.swing.JOptionPane;
import sunnycss.MODEL.LoaiSP;
import sunnycssw.DAO.QuanLyDAO;

/**
 *
 * @author hai95
 */
public class dg_ThemLoai extends java.awt.Dialog {

    /**
     * Creates new form dg_ThemLoai
     */
    public int index;
    public LoaiSP lsp = new LoaiSP();
    public QuanLyDAO qlmodel = new QuanLyDAO();

    public dg_ThemLoai(java.awt.Frame parent, boolean modal, int index, LoaiSP lsp) {
        super(parent, modal);
        initComponents();
        setSize(400, 350);
        setLocationRelativeTo(null);
        this.lsp = lsp;
        this.index = index;
        txtIDLoai.setEnabled(false);
        if (this.index == 1) {
            lblTitle.setText("Thêm loại");
            clearForm();
        } else if (this.index == 2) {
            lblTitle.setText("Cập nhật loại");
            setForm();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenLSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAMota = new javax.swing.JTextArea();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIDLoai = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thêm Loại Sản Phẩm");
        add(lblTitle);
        lblTitle.setBounds(20, 30, 360, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên Loại");
        add(jLabel2);
        jLabel2.setBounds(20, 130, 70, 25);

        txtTenLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtTenLSP);
        txtTenLSP.setBounds(100, 130, 280, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mô tả");
        add(jLabel3);
        jLabel3.setBounds(20, 170, 70, 25);

        txtAMota.setColumns(20);
        txtAMota.setRows(5);
        jScrollPane1.setViewportView(txtAMota);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 170, 280, 90);

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Accept.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu);
        btnLuu.setBounds(60, 280, 100, 25);

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        add(btnHuy);
        btnHuy.setBounds(230, 280, 90, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID Loại");
        add(jLabel4);
        jLabel4.setBounds(20, 90, 70, 25);

        txtIDLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtIDLoai);
        txtIDLoai.setBounds(100, 90, 280, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        Luu();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed
    public void setForm() {
        txtIDLoai.setText(lsp.getIdLoai() + "");
        txtTenLSP.setText(lsp.getTenLoai());
        txtAMota.setText(lsp.getMoTa());
    }

    public LoaiSP getForm() {
        lsp.setTenLoai(txtTenLSP.getText());
        lsp.setMoTa(txtAMota.getText());
        return lsp;
    }

    public void Luu() {
        if (!check()) {
            return;
        }
        if (index == 1) {
            qlmodel.addLSP(getForm());
        } else if (index == 2) {
            qlmodel.updateLSP(getForm());
        }
        setVisible(false);
        dispose();
        pnlQuanLy.pnQlLy.updateUI();
    }

    public void clearForm() {
        txtIDLoai.setText("");
        txtTenLSP.setText("");
        txtAMota.setText("");
    }

    public boolean check() {
        if (txtTenLSP.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên Loại không được để trống");
            txtTenLSP.requestFocus();
            return false;
        }
        if (txtAMota.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mô tả không được để trống");
            txtAMota.requestFocus();
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtAMota;
    private javax.swing.JTextField txtIDLoai;
    private javax.swing.JTextField txtTenLSP;
    // End of variables declaration//GEN-END:variables
}
