CREATE DATABASE QLSUNNY

---BẢNG NHÂN VIÊN
IF OBJECT_ID('nhanvien') IS NOT NULL
	DROP TABLE nhanvien
GO
CREATE TABLE nhanvien
(
	IDNV	VARCHAR(10) NOT NULL ,
	HOTEN	NVARCHAR(50) NOT NULL,
	PASS	VARCHAR(20) NOT NULL,
	NGAYSINH	DATETIME NOT NULL,
	DIACHI	NVARCHAR(50) NOT NULL,
	GIOITINH	BIT NOT NULL,
	ROLES	NVARCHAR(30) NOT NULL,
	SDT		VARCHAR(12) NOT NULL,
	working bit not null
	CONSTRAINT Pk_nhanvien PRIMARY KEY(IDNV)
)


---BANG SANPHAM
IF OBJECT_ID('LOAISANPHAM') IS NOT NULL
	DROP TABLE LOAISANPHAM
GO
CREATE TABLE LOAISANPHAM
(
IDLOAI		INT NOT NULL IDENTITY(1,1),
TENLOAI		NVARCHAR(50) NOT NULL,
MOTA		NVARCHAR(100) NOT NULL,
trangthai	bit not null
CONSTRAINT PK_LOAISANPHAM PRIMARY KEY(IDLOAI)
)
-----reset identity
TRUNCATE TABLE DBO.LOAISANPHAM

---BANG SAN PHAM
IF OBJECT_ID('SANPHAM') IS NOT NULL
	DROP TABLE SANPHAM
GO
CREATE TABLE SANPHAM
(
IDSP	INT NOT NULL IDENTITY(1,1),
TENSP	NVARCHAR(100) NOT NULL,
XUATXU	NVARCHAR(30) NOT NULL,
HANGSX	NVARCHAR(30) NOT NULL,
TTKHAC	NVARCHAR(100) NOT NULL,
DONGIA	int null,
IDLOAI		INT NOT NULL,
trangthai	bit not null
CONSTRAINT PK_SANPHAM PRIMARY KEY(IDSP)
CONSTRAINT FK_LOAISANPHAM_SANPHAM FOREIGN KEY(IDLOAI) REFERENCES DBO.LOAISANPHAM
)
-----reset identity
TRUNCATE TABLE DBO.SANPHAM

---BANG HOA DON
 IF OBJECT_ID('HOADON') IS NOT NULL
 DROP TABLE HOADON
 GO
 CREATE TABLE HOADON
 (
 IDHOADON INT NOT NULL IDENTITY(1,1),
 NGAYLAPHD DATETIME NOT NULL,
 IDNV VARCHAR(10) NOT NULL,
 TRANGTHAI	BIT NULL
 CONSTRAINT PK_HOADON PRIMARY KEY(IDHOADON),
 CONSTRAINT FK_NHANVIEN_HOADON FOREIGN KEY (IDNV) REFERENCES DBO.NHANVIEN
 )
 --reset identity
TRUNCATE TABLE DBO.HOADON

---BANG HOADONCT
IF OBJECT_ID('HOADONCT') IS NOT NULL
 DROP TABLE HOADONCT
 GO
 CREATE TABLE HOADONCT
 (
 IDHOADON	INT NOT NULL,
 IDSP		INT NOT NULL,
 SOLUONG	INT NOT NULL
 CONSTRAINT FK_HOADON_HOADONCT FOREIGN KEY(IDHOADON) REFERENCES DBO.HOADON,
 CONSTRAINT FK_SANPHAM_HOADONCT FOREIGN KEY(IDSP) REFERENCES DBO.SANPHAM,
 CONSTRAINT PK_HOADONCT PRIMARY KEY(IDHOADON, IDSP)
)
 --reset identity

DELETE FROM NHANVIEN

INSERT INTO DBO.NHANVIEN (IDNV,HOTEN,PASS,NGAYSINH,DIACHI,GIOITINH,SDT,ROLES, working)
VALUES('HAILV',N'LÊ VĂN HAI','PH13040','10-09-1995',N'HÀ NỘI',1,'0987654321',N'QUẢN LÝ',1),
('NGHIADH',N'ĐÀO HỮU NGHĨA','PH13041','10-09-1996',N'THÁI BÌNH',1,'0987654320',N'NHÂN VIÊN',1),
('DAICV',N'CHU VĂN ĐÀI','PH12986','10-09-1997',N'HÀ NỘI',1,'0987654322',N'NHÂN VIÊN',1),
('QUANGVM',N'VŨ MINH QUANG','PH130996','10-09-1998',N'HÀ NỘI',1,'0987654321',N'NHÂN VIÊN',1)


DELETE FROM LOAISANPHAM

INSERT INTO DBO.LOAISANPHAM (TENLOAI,MOTA,trangthai)
VALUES(N'Nước Hoa',N'Sản phẩm thể lỏng, mùi thơm',1),
(N'Son Môi',N'Sản Phẩm dùng để dưỡng môi',1),
(N'Phấn',N'Sản phẩm dạng bột dùng để che khuyết điểm',1),
(N'Kem Dưỡng Da',N'Sản phẩm dạng Gel, dùng để dưỡng da',1)

DELETE FROM SANPHAM
INSERT INTO DBO.SANPHAM(TENSP,XUATXU,HANGSX,TTKHAC, DONGIA,IDLOAI,trangthai)
VALUES(N'Nước hoa GUCCI',N'Pháp',N'GUCCI',N'Nước hoa nữ', 750000,1,1),
(N'Nước hoa DIOR',N'PHÁP',N'DIOR',N'Nước hoa nữ', 650000,1,1),
(N'Nước hoa BLEU DE CHANNEL',N'NHẬT',N'CHANEL',N'Nước hoa nam', 1000000,1,1),
(N'Son Christian Louboutin',N'PHÁP',N'CHRISTIAN',N'son nữ', 300000,2,1),
(N'Son Tom Ford ',N'Ý',N'TF',N'Son môi được ưa chuộng số 1 tại Ý',550000,2,1),
(N'Phấn Cover CC Cushion',N'Ý',N'GUCCI',N'Phấn che khuyết điểm dạng nước', 1150000,3,1),
(N'Phấn Sulwhasoo Perfecting Cushion',N'PHÁP',N'CHANEL',N'Phấn nước dùng cho da dầu', 650000,3,1),
(N'Kem dưỡng da mặt Neutrogena',N'NHẬT',N'Johnson& Johnson',N'Kem dưỡng da phù hợp mọi loại da',350000,4,1),
(N'Kem dưỡng da mặt Innisfree',N'HÀN QUỐC',N'EX',N'Kem dưỡng da số 1 Hàn Quốc', 2000000,4,1)

DELETE FROM HOADON
INSERT INTO DBO.HOADON(NGAYLAPHD,IDNV,TRANGTHAI)
VALUES('03-05-2021','NGHIADH',1),
('04-05-2021','QUANGVM',1),
('05-05-2021','DAICV',1)


 DELETE FROM HOADONCT
 INSERT INTO DBO.HOADONCT(IDHOADON,IDSP,SOLUONG) VALUES(2,2,10)
 INSERT INTO DBO.HOADONCT(IDHOADON,IDSP,SOLUONG) VALUES(2,4,5)
 INSERT INTO DBO.HOADONCT(IDHOADON,IDSP,SOLUONG) VALUES(3,6,1)
 INSERT INTO DBO.HOADONCT(IDHOADON,IDSP,SOLUONG) VALUES(3,8,2)








 SELECT*FROM NHANVIEN
 SELECT*FROM SANPHAM
 SELECT*FROM LOAISANPHAM
 SELECT*FROM HOADON
 SELECT*FROM HOADONCT

